# Generated by Django 4.1.6 on 2023-06-01 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_text', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordgame.dictionary')),
            ],
        ),
    ]
